pipeline:
  identifier: Build_python_pipeline_samples_1685095567586
  name: Build python-pipeline-samples
  orgIdentifier: default
  projectIdentifier: pythondemo
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1685095550497
        repoName: Mithun-rinky/python-pipeline-samples
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      repo: hello/world
                      tags: latest
                  timeout: ""
                  type: Plugin
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
